version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:00"
      timezone: "Europe/Paris"
    allow:
      - dependency-type: "all"
